---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot2b-sep17-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot2b-sep17-1 
  name: chatbot2b-sep17-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi