apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot2b-sep17-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot2b-sep17-1:f6825dff8cd7a4952c035dfe4f436e922726c506@sha256:0761ad108abef1387b002fb7f7edb9ed81e7797a25f3fdbf41b5b1996f594b79 # use pre-built to bootstrap 
          name: app-inference
